name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: Build UACME

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

name: Build UACME

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build UACME Project
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution (x64 Release)
        run: |
          msbuild Source\UACME.sln ^
            /p:Configuration=Release ^
            /p:Platform=x64 ^
            /p:PlatformToolset=v143 ^
            /p:WindowsTargetPlatformVersion=10.0.19041.0

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UACME-x64-Release
          path: |
            Source\bin\
            Source\**\x64\Release\*.exe
            Source\**\x64\Release\*.dll
